### PR TITLE
Deleted C4:A8:1D:xx:xx:xx from asus pin

### PR DESCRIPTION
**Pull request by alcomic**

### CODE REVIEW

**Comment by Felis-Sapiens** [comment]
Look at C4:A8:1D:2E:_, C4:A8:1D:4D_, C4:A8:1D:E5_, C4:A8:1D:E9_, ...

**Comment by alcomic** [comment]
Hmmm. D-Link use asus algorithm? http://pix.my/vNgJPP5x http://pix.my/esTT3nQ0 then merge another pull requests

**Comment by binarymaster** [comment]
Can't check these MACs right now, I'll be able to do it next day. Thanks!

**Comment by Felis-Sapiens** [comment]
> Hmmm. D-Link use asus algorithm?

Only with Airocon firmware

**Pull request closed without merging**
